const path = require('path')
const fs = require('fs')

/**
 * @typedef SamplesState
 * @property {Array<AudioSampleInfo>} samples
 * @property {Array<AudioSampleInfo>} music
 */

/**
 * @typedef AudioSampleInfo
 * @property {string} name
 * @property {string} id
 */

/**
 * @returns {SamplesState}
 */
const getDefaultState = () => {
  return {
    /** @type {Array<AudioSampleInfo>} */
    samples: [],
    /** @type {Array<AudioSampleInfo>} */
    music: [],
  }
}

/**
 * @param {string} dirPath
 * @returns {Array<string>}
 */
const getFiles = (dirPath) => {
  const files = fs.readdirSync(dirPath, (err, files) => {
    if (err) {
      throw err
    }

    return files
  })

  return sortFileNames(files)
}

/**
 *
 * @param {Record<keyof SamplesState, string>} paths
 * @returns {SamplesState}
 */
const getState = (paths) => {
  const state = getDefaultState()

  Object.entries(paths).forEach(
    /**
     * @param {keyof SamplesState} key
     * @param {string} path
     */
    ([key, path]) => {
      getFiles(path).forEach((sampleFileName) => {
        /** @type {AudioSampleInfo} */
        const info = {
          name: sampleFileName,
          id: 'id' + (Math.random() * Math.random()),
        }
        state[key].push(info)
      })
    })

  return state
}

/**
 * @param {SamplesState} state
 * @returns {string}
 */
const getScriptFileContent = (state) => {
  // That was the moment I started regretting I hadn't used frameworks
  return [
    '/** THIS FILE IS AUTOGENERATED, CHECK THE README */',
    '/** @type {SamplesState} */',
    `const SAMPLES_STATE = ${JSON.stringify(state, null, ' ')};`,
  ].join('\n')
}

/**
 * Sort by the numerical indexes if the filename starts with a number
 * @param {Array<string>} files
 * @return {Array<string>}
 */
const sortFileNames = (files) => {
  return files.sort((a, b) => {
    const indexA = (a.match(/^(\d+)/) || [])[1]
    const indexB = (b.match(/^(\d+)/) || [])[1]

    if (typeof indexA !== 'undefined' && typeof indexB !== 'undefined') {
      return +indexA - +indexB
    }
    if (typeof indexA !== 'undefined') {
      return -1
    }
    if (typeof indexB !== 'undefined') {
      return 1
    }

    return a[0] - b[0]
  })
}

const main = () => {
  const samplesDirName = 'samples'
  const musicDirName = 'music'
  const webAppRootPath = path.join(__dirname, '..')

  /** @type {Record<keyof SamplesState, string>} */
  const paths = {
    samples: path.join(webAppRootPath, samplesDirName),
    music: path.join(webAppRootPath, musicDirName),
  }

  const state = getState(paths)
  fs.writeFileSync(
    path.join(webAppRootPath, 'js', 'samples.js'),
    getScriptFileContent(state),
  )
}

main()
